### ISSUE TITLE
Hex is not a function on ObjectId creation

### ISSUE THREAD

**Issue by thundo** [mongodb/js-bson#204]
I'm getting a `TypeError: hex is not a function` using the mongo node driver with
 ```js
new ObjectId('586bc0c7c7a9ab00da14d1d2');
```
It stopped working between 1.0.1 and 1.0.2 of this library. Platform: Linux, Node v. 4.3.2

May be related to changes of #201.

Thanks

**Comment by ahmadferdous** [comment]
I got the same error when I did a fresh npm install today. The stack trace points to bson. Can you please take a look?
```
/xyz/node_modules/mongoose/node_modules/bson/lib/bson/objectid.js:52
    return new ObjectID(Buffer.from(id, 'hex'));
                               ^

TypeError: hex is not a function
    at Function.from (native)
    at Function.from (native)
    at new ObjectID (/xyz/node_modules/mongoose/node_modules/bson/lib/bson/objectid.js:52:32)
    at ObjectID (/xyz/node_modules/mongoose/node_modules/bson/lib/bson/objectid.js:31:42)
```
```
⇒  npm view bson version
1.0.3
```
Node v4.2.4, on Mac.

**Comment by ahmadferdous** [comment]
I have created a pull request to fix this issue: https://github.com/mongodb/js-bson/pull/205

**Comment by ahmadferdous** [comment]
The following outputs true in Nodejs v4.2.4. 
```
var hasBufferType = false;
if(Buffer && Buffer.from) hasBufferType = true;
console.log(hasBufferType);
```

**Comment by jefarmstrong** [comment]
I'm running v4.3.2 in production and (Buffer && Buffer.from) also returns true
but Buffer.from('123', 'hex') fails with 'TypeError: hex is not a function'

**Comment by alexdonei** [comment]
I've the same problem ('TypeError: hex is not a function') with v4.4.6 in production, with v4.6.1 il local env I don't have problem.

**Comment by JvrBaena** [comment]
Same here. This issue is breaking ObjectId validation/generation for everyone using Mongoose >= 4.7.3. The `hex is not a function` error is catched as a CastError when generating any ObjectId from Strings. See here https://github.com/Automattic/mongoose/issues/4860 and here https://github.com/Automattic/mongoose/issues/4867

Would be great if we could get https://github.com/mongodb/js-bson/pull/205 (or another solution for this) merged :)

Thanks!

**Comment by Kikobeats** [comment]
NodeJS API for Buffer is inconsistent between node versions.

A better approach is use [buffer](https://www.npmjs.com/package/buffer) (thanks @feross!) package that do exactly the same (or better) and move the dependency out of the native API. 

It was designed precisely for this kind of problems as premise.

**Comment by applicity** [comment]
For information seems to also be broken in 4.7.1

**Comment by Gormartsen** [comment]
node v5.4.1
mongodb package.

`new ObjectID('24lenghIdKeyHere')`
generate 
`TypeError: hex is not a function `

PR: https://github.com/mongodb/js-bson/pull/205
Fixed issue.

**Comment by feross** [comment]
@Kikobeats Although `buffer` works in node, it reimplements the entire API, and it's intended for browser usage. It will be faster to use `safe-buffer` which just shims the missing Buffer methods, and only does it when necessary.

https://www.npmjs.com/package/safe-buffer

**Comment by jiffify** [comment]
same error on ubuntu but works fine in windows.

Uncaught TypeError: hex is not a function
      at Function.from (native)
      at Function.from (native)
      at new ObjectID (node_modules/bson/lib/bson/objectid.js:52:32)

**Comment by ahmadferdous** [comment]
@jiffify : what node versions do you have on ubuntu and windows?

**Comment by gregbanks** [comment]
according to issue https://github.com/nodejs/node/issues/8053, these APIs have been backported to node versions > **4.5.0**

works for me on osx with node 4.5.0 and above.

**Comment by mrapptambour** [comment]
I would like to second a fix on this subject. Updating from mongodb 2.2.12 to 2.2.13 is where the bump from bson 0.5.* to 1.* occurs. Running Node v4.3.2 (AWS Lambda Runtime Environment) includes the same error:

```
     TypeError: hex is not a function
      at Function.from (native)
      at Function.from (native)
      at new ObjectID (node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/objectid.js:52:32)
```

**Comment by jiffify** [comment]
@ahmadferdous 

For windows node version is 4.5.0
For ubuntu node version is 4.2.6

**Comment by ahmadferdous** [comment]
@jiffify : The error on ubuntu makes sense based on what @gregbanks told. APIs have been backported to node versions >= 4.5.0. That's why it worked on windows (node v4.5.0) but not ubuntu (node v 4.2.6).

**Comment by christkv** [comment]
fixed and released in 1.0.4, broken due to early 4.x node Buffer.from throwing on hex encoding. driver 2.2.20 released to include it.

**Comment by kaankocturk** [comment]
so guys I'm new to github and I'm having the same problem. If you have found the cure, how can I fix it?

**Comment by christkv** [comment]
upgrade you node to the latest 4.x version. this is caused by a bug in early 4.x versions.

**Comment by kaankocturk** [comment]
I love you guys. I would never be able to do this if it werent for the community. Much love.
